### ISSUE TITLE
Install not working because of missing qtpaths6

### ISSUE THREAD

**Issue by colorcube** [eclipseo/reimage#1]
```
./install.sh: line 24: qtpaths6: command not found
./install.sh: line 25: qtpaths-qt6: command not found
./install.sh: line 26: qtpaths-qt6: command not found
Installing kde-service-menu-reimage system wide
install: target '' is not a directory: No such file or directory
Done!. kde-service-menu-reimage has been installed. Enjoy!

```

KDE Neon
I guess there's a package I need to install?

PS: Thanks very much to revive this service menu!!

**Comment by colorcube** [comment]
Found this

https://bugs.kde.org/show_bug.cgi?id=482393

qtpaths6 seems to be in qt6-base-dev-tools package. Unfortunately that has a ton of dev dependencies.

I'm unsure what the right solution is.

**Comment by eclipseo** [comment]
Qtpaths6 was a typo

On my system it is qtpaths-qt6. I'm not sure how it is name on other distro.

**Comment by colorcube** [comment]
Well the problem is not solved.

It seems on Kubuntu and KDE Neon it's _qtpaths6_ but **only** if you have QT dev packages installed, which is normally not the case and therefore the install will fail.

How about using default paths as fallback if qtpaths6/qtpaths-qt6 is not available?

~/.local/share/kio/servicemenus
/usr/share/kio/servicemenus

**Comment by dcrobertson01** [comment]
so any progress on this? I've tried installing from the dolphin interface and from the command line.

```
./install.sh: line 24: qtpaths6: command not found
./install.sh: line 25: qtpaths6: command not found
./install.sh: line 26: qtpaths6: command not found
Installing kde-service-menu-reimage system wide
install: target '': No such file or directory
Done!. kde-service-menu-reimage has been installed. Enjoy!

```
